// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICharacterSystem {
  function addCharacterMud() external;

  function updateCharacterPositionMud(bytes32 characterId, int32 x, int32 z) external;

  function getCurrentCharacterIdMud() external view returns (bytes32);
}
